### ISSUE TITLE
null is not an object (evaluating' reactNative.NativeModules.NativeMobileSDKBridge.startMeeting')

### ISSUE THREAD

**Issue by devsonuyadav** [aws-samples/amazon-chime-react-native-demo#171] opened 2023-01-10 07:41 UTC
I have integrated the amazon sdk in react native. I have followed this step : https://github.com/aws-samples/amazon-chime-react-native-demo#2-add-sdk-binaries-to-the-project. 

Step to reproduce : 
1. add sdk to the project.
2. Add this folder to the project :  https://github.com/aws-samples/amazon-chime-react-native-demo/tree/master/src

Screenshot of the issue : 
![Screenshot 2023-01-03 at 12 19 22 AM 2](https://user-images.githubusercontent.com/33959693/211490085-c01924c4-9430-48d9-ab40-167def17657b.png)

Environment Setup : 

React Native : 0.68.8
SDK version : 0.17.9
React : 17.0.2
Mac Version : 12.4
buildToolsVersion = "31.0.0"

Build Gradle : 
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 31
ndkVersion = "21.4.7075529"

Note : I have already reinstalled node_modules and gradlew clean

**Comment by hokyungh** [comment] 2023-01-19 02:33
Thanks for reporting. We'll take a look and get back to you.

**Comment by hokyungh** [comment] 2023-01-19 21:55
Hi I have tried on my machine, but I wasn't still able to do reproduce the same. 

I have tried with node v16.16.0 and tried on following PR and see if it works for you?
https://github.com/aws-samples/amazon-chime-react-native-demo/pull/173

**Comment by devsonuyadav** [comment] 2023-01-23 11:53
Hi @hokyungh, I am sharing a video for you to check the things which we have done. We have degraded the node version from the 19.4.0 to 16.16.0 as mentioned and also upgraded the Amazon chime to 

1. 'software.aws.chimesdk:amazon-chime-sdk:0.17.9' 
2. 'software.aws.chimesdk:amazon-chime-sdk-media:0.17.10'

Still its running the same error as you can see in the video recording 

Please advice what needs to be done from our end 
[amazon_chime-Integration-error.mp4.zip](https://github.com/aws-samples/amazon-chime-react-native-demo/files/10479326/amazon_chime-Integration-error.mp4.zip)

**Comment by hokyungh** [comment] 2023-01-23 17:58
Could you share minimal demo where you are having issue? Based on the video, I don't think it was using the PR I published.

**Comment by devsonuyadav** [comment] 2023-01-24 17:58
Here is the full uses video of  library as well as setup part 

https://drive.google.com/file/d/146yD8w5s7e_yPfz4E40oGXTamG1bOaNQ/view?usp=sharing

**Comment by hokyungh** [comment] 2023-01-25 01:09
Hi for minimal demo I wanted some repo which I can run it locally. Based on the video, it is hard to know what you have copied and what is missing. For example, do you have [code1](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/c9ebead35d5505fae54fa11d4e255cd8f33f68d3/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt) and [code2](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/7cf2944bd77068041260c62e0b00011bdacab06f/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridgePackage.kt)? When you build android, do you see these files getting built from the logs?

**Comment by devsonuyadav** [comment] 2023-01-31 07:35
Hi @hokyungh, here is the demo application that I have created with the same configuration of our current application. 
https://github.com/devsonuyadav/chimesdk.git. Please let me know if anything more information required

**Comment by hokyungh** [comment] 2023-02-02 22:57
Hi @devsonuyadav, I have taken a look at your repo, but looks like it is missing a lot of files as described [here](https://github.com/aws-samples/amazon-chime-react-native-demo#android-4). I don't see files like

* NativeMobileSDKBridge.kt:Functions that will be available in React Native through Native Module.
* RNEventEmitter.kt: Utility class that provides helper to send events to React Native.
* MeetingObservers.kt: Event handlers to pass Amazon Chime SDK events into React Native.
* RNVideoViewManager.kt: UI component manager.
* NativeMobileSDKBridgePackage.kt:  Package definition to register the bridge in the Android application.

Could you add these and retest? You might need to change the package name and import.

You can compare the files [rndemo](https://github.com/aws-samples/amazon-chime-react-native-demo/tree/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo) and [chimesdk](https://github.com/devsonuyadav/chimesdk/tree/main/android/app/src/main/java/com/awesomeproject) to see which files are missing.

**Comment by equilizer** [comment] 2023-02-07 11:14
facing the same problem...trying a workaround if found will post here.

**Comment by equilizer** [comment] 2023-02-08 09:51
able to solve following the steps above.

**Comment by hokyungh** [comment] 2023-02-14 22:24
I'll close this issue since I wasn't able to reproduce from my side. Feel free to reopen if you still face issue. @equilizer do you mind opening new issue for it with repro steps?

**Closed by hokyungh** 2023-02-14 22:24 UTC
Labels: Needs More Information, Android
