### ISSUE TITLE
Destitution failed w ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by devgauravs** [aws-samples/amazon-chime-react-native-demo#179] opened 2023-02-23 13:51 UTC
**Describe the bug**
When submitting to Apple you get the error ITMS-90338. Doing a distribution

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia: terminate. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at

also i raised the issue on 
https://github.com/aws/amazon-chime-sdk-ios/issues/443

**Comment by zhinang-amazon** [comment] 2023-02-23 19:14
This is a duplicate of https://github.com/aws/amazon-chime-sdk-ios/issues/552
Please upgrade to the latest AmazonChimeSDK and AmazonChimeSDKMedia packages and let us know if that's still an issue.

**Closed by zhinang-amazon** 2023-02-23 19:14 UTC
