### ISSUE TITLE
could not invoke NativeMobileSDKBridge.startMeeting - chime integration in existing react-native project(Android)

### ISSUE THREAD

**Issue by SuhailBt** [aws-samples/amazon-chime-react-native-demo#60] opened 2021-02-24 13:35 UTC
Getting this error when trying to start meeting. Attaching screenshot for the reference 
![Screenshot from 2021-02-24 18-01-46](https://user-images.githubusercontent.com/65166275/109008355-40118880-76d3-11eb-8910-711133f7c1d2.png)

**Comment by timorss** [comment] 2021-02-24 15:17
I have similar issue, not exactly the same,
should I open another issue about that?
![WhatsApp Image 2021-02-24 at 17 16 16](https://user-images.githubusercontent.com/13855015/109022064-2583e300-76c4-11eb-86f9-bbe6c11dacaa.jpeg)

**Comment by Devo-React** [comment] 2021-02-24 16:23
I am also having same issue when I test on my real device.

**Comment by hokyungh** [comment] 2021-02-24 19:04
Hi @SuhailBt Could you check if you are running real devices or simulator with ARM support? As mentioned [here](https://github.com/aws/amazon-chime-sdk-android#running-the-demo-app), we do not support x86.

@timorss Your issue looks different. It might be that your app `build.gradle` might be missing 
```
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.3'
```

@Devo-React Which error are you getting?

We'll try to update the documentation to ease this process.

**Comment by Devo-React** [comment] 2021-02-24 19:11
![WhatsApp Image 2021-02-24 at 8 10 10 PM](https://user-images.githubusercontent.com/79227927/109052951-7c95b200-76dc-11eb-9d74-854ae4cd3dcb.jpeg)

**Comment by hokyungh** [comment] 2021-02-24 19:47
@Devo-React Could you check adding
```
dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.3'
    implementation 'androidx.core:core-ktx:1.1.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

in `app/build.gradle` fixes the issue?

**Comment by Devo-React** [comment] 2021-02-24 20:01
> dependencies {
>     implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.3'
>     implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.3'
>     implementation 'androidx.core:core-ktx:1.1.0'
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.71"
> }

I have added above dependencies in app/build.gradle but still I am getting same error.

**Comment by hokyungh** [comment] 2021-02-24 20:31
oh my bad. 
Could you also add `implementation 'com.google.code.gson:gson:2.8.6'`

**Comment by Devo-React** [comment] 2021-02-24 21:13
> implementation 'com.google.code.gson:gson:2.8.6'

Yes this resolved the error.

But app is crashing.
Log doesn't give any errors.

`I/ChimeReactNativeSDKDemoManager: Called startMeeting
I/ChimeReactNativeSDKDemoManager: { NativeMap: {"AudioHostUrl":"522ff1148f5aff4b0b61096589fcc24d.k.m3.ue1.app.chime.aws:3478","AudioFallbackUrl":"wss://haxrp.m3.ue1.app.chime.aws:443/calls/5e7ca3d5-68a7-4736-b531-9f1e9f4f00e1","ScreenDataUrl":"wss://bitpw.m3.ue1.app.chime.aws:443/v2/screen/5e7ca3d5-68a7-4736-b531-9f1e9f4f00e1","ScreenSharingUrl":"wss://bitpw.m3.ue1.app.chime.aws:443/v2/screen/5e7ca3d5-68a7-4736-b531-9f1e9f4f00e1","ScreenViewingUrl":"wss://bitpw.m3.ue1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=5e7ca3d5-68a7-4736-b531-9f1e9f4f00e1","SignalingUrl":"wss://signal.m3.ue1.app.chime.aws/control/5e7ca3d5-68a7-4736-b531-9f1e9f4f00e1","TurnControlUrl":"https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions"} }
D/AudioClient: [AudioClient.java] break here
I/audioclient_jni: xal_android init. Android Api Version is 28
I/connectreactap: Thread[29,tid=8868,Native,Thread*=0x7e17610400,peer=0x13034a38,"mqt_native_modules"] recursive attempt to load library "/data/app/com.connectreactapp-dr1OKSXb3Nt9cP95Qglifw==/lib/arm64/libamazon_chime_media_client.so"
I/videoclient_jni: VideoClientJNI_OnLoad called....OK
I/videoclient_jni: Load complete for video client jni
I/audioclient_jni: [audio client] INTIALIZED
I/AudioClient: SPK LAT: 80.5(ms) MIC LAT: 40.0(ms)
I/AudioClient: SPK LAT: 80.083336(ms) MIC LAT: 40.0(ms) NATIVE SR: 48000
I/AudioManager: In isSpeakerphoneOn(), calling application: com.connectreactapp
I/CameraManagerGlobal: Connecting to camera service
W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 2
    [soar.cts] ignore the status update of camera: 3
D/AudioManager: PPD setMode mode = 3
V/AudioManager: Elem: dalvik.system.VMStack.getThreadStackTrace(Native Method)
    Elem: java.lang.Thread.getStackTrace(Thread.java:1538)
    Elem: android.media.AudioManager.setMode(AudioManager.java:1831)
    Elem: com.amazonaws.services.chime.sdk.meetings.device.DefaultDeviceController.<init>(DefaultDeviceController.kt:73)
    Elem: com.amazonaws.services.chime.sdk.meetings.device.DefaultDeviceController.<init>(DefaultDeviceController.kt:32)
    Elem: com.amazonaws.services.chime.sdk.meetings.session.DefaultMeetingSession.<init>(DefaultMeetingSession.kt:106)
    Elem: com.amazonaws.services.chime.sdk.meetings.session.DefaultMeetingSession.<init>(DefaultMeetingSession.kt:34)
    Elem: com.connectreactapp.NativeMobileSDKBridge.startMeeting(NativeMobileSDKBridge.kt:74)
    Elem: java.lang.reflect.Method.invoke(Native Method)
    Elem: com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    Elem: com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    Elem: com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    Elem: android.os.Handler.handleCallback(Handler.java:873)
    Elem: android.os.Handler.dispatchMessage(Handler.java:99)
    Elem: com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    Elem: android.os.Looper.loop(Looper.java:193)
    Elem: com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    Elem: java.lang.Thread.run(Thread.java:764)
I/DefaultAudioClientController: spkMinBufSizeInSamples 3844 micMinBufSizeInSamples 1920
I/DefaultVideoClientController: Initializing video client
I/DefaultVideoClientController: Starting video client
I/videoclient_jni: video client - startService:
    Reported App Detail Info: { app_version_name: Android 1.0, app_version_code: 1, device_model: ONEPLUS A6013, device_make: OnePlus, platform_name: android, platform_version: 9, client_source: amazon-chime-sdk, chime_sdk_version: 0.8.2 }
W/Logging: HardwareVideoEncoderFactory: No shared EglBase.Context.  Encoders will not use texture mode.
D/: PlayerBase::PlayerBase()
    TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x1 based on channel count of 1)
D/AudioTrack: set(): streamType 0, sampleRate 16000, format 0x1, channelMask 0x1, frameCount 0, flags #104, notificationFrames -2, sessionId 20105, transferType 0, uid -1, pid -1
W/VideoCapabilities: Unsupported mime image/vnd.android.heic
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
    Unrecognized profile 2130706434 for video/avc
W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 644
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
    Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unsupported mime video/divx
W/libOpenSLES: Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
W/VideoCapabilities: Unsupported mime video/divx4
W/VideoCapabilities: Unrecognized profile 4 for video/hevc
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
    Unrecognized profile 2130706434 for video/avc
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/audioclient_jni: MEDIA STREAM STATE CALLBACK IN C STATE IS 1
I/DefaultAudioClientObserver: AudioClient State: Connecting Status: OK
I/DefaultVideoClientObserver: requestTurnCreds
I/DefaultAudioClientController: Started audio session.
I/DefaultVideoClientController: Starting remote video
I/Logging: EglBase14Impl: Using OpenGL ES version 2
I/DefaultVideoClientObserver: Making TURN Request
I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
I/DefaultVideoClientObserver: User Agent while doing TURN request is Dalvik/2.1.0 (Linux; U; Android 9; ONEPLUS A6013 Build/PKQ1.180716.001)
D/audioclient_jni: MEDIA STREAM STATE CALLBACK IN C STATE IS 2
I/DefaultAudioClientObserver: AudioClient State: FinishConnecting Status: OK
I/MeetingObservers: Received event for audio session started. Reconnecting: false
I/DefaultVideoClientObserver: TURN Request Success
I/videoclient_jni: video client - updateTurnCredentials:
    video client - allocating memory for urisBuf
    Updating TURN creds: { user_name: 1614201246:6a307595-8544-4bb2-b21b-313261bbe5aa, signaling_url: wss://signal.m3.ue1.app.chime.aws/control/5e7ca3d5-68a7-4736-b531-9f1e9f4f00e1 }
I/videoclient_jni: video client - free the allocated memory for urisBuf
W/RenderThread: type=1400 audit(0.0:4003168): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=15924 scontext=u:r:untrusted_app:s0:c227,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
W/RenderThread: type=1400 audit(0.0:4003169): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=15924 scontext=u:r:untrusted_app:s0:c227,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/videoclient_jni: video client DNS: dns1 , dns2 
I/DefaultVideoClientObserver: isConnecting
E/videoclient_jni: video client DNS: dns1 , dns2 
D/DefaultAudioClientObserver: Added: AttendeeInfo(attendeeId=1cb92ab8-327a-0788-6d76-b128a8d47404, externalUserId=1bc2c7fc#test10)
I/MeetingObservers: Received attendee join event for attendee: 1cb92ab8-327a-0788-6d76-b128a8d47404 with externalUserId 1bc2c7fc#test10
I/DefaultVideoClientObserver: didConnect with controlStatus: 0
D/DefaultVideoClientObserver: cameraSendIsAvailable: true
D/DefaultVideoClientObserver: cameraSendIsAvailable: true
E/SensorManager: unregisterListenerImpl callingApp: com.connectreactapp,callingPid:8729,callingUid:10227
I/ReactNativeJNI: Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
`

**Comment by hokyungh** [comment] 2021-02-24 21:51
@Devo-React Thank you for the report. Do you actually mind opening another issue for this? Do you have extra device to test whether this is reproducible in other devices?

**Comment by Devo-React** [comment] 2021-02-24 22:51
> Thank you for the report. Do you actually mind opening another issue for this? Do you have extra device to test whether this is reproducible in other devices?

Sorry, it was my mistake in rendering the view.
Working fine now... thanks!

**Comment by SuhailBt** [comment] 2021-02-25 06:43
@hokyungh : that issue is resolved. Thanks a lot. But I am facing another meeting is not getting started. Listening to onError listener when trying to start meeting.

**Comment by SuhailBt** [comment] 2021-02-25 07:15
adding some code for your reference

  NativeFunction.startMeeting(meetingJson, attendeeJson);

"meetingJson": {
        "ResponseMetadata": {
          "RequestId": "id here",
          "HTTPStatusCode": 201,
          "HTTPHeaders": {
            "x-amzn-requestid": "id here from response",
            "content-type": "application/json",
            "content-length": "841",
            "date": "Thu, 25 Feb 2021 06:51:27 GMT"
          },
          "RetryAttempts": 0
        },
        "Meeting": {
          "MeetingId": "meeting id here,
          "ExternalMeetingId": "external meeting id here",
          "MediaPlacement": {
            "AudioHostUrl": "4df0",
            "AudioFallbackUrl": "wss://haxrp.m...",
            "ScreenDataUrl": "wss://bit...",
            "ScreenSharingUrl": "wss:/...",
            "ScreenViewingUrl": "wss://bitp...",
            "SignalingUrl": "wss://sig...",
            "TurnControlUrl": "ht..."
          },
          "MediaRegion": "..."
        }
      },

"attendeeJson": {
        "Attendee": {
          "JoinToken": "....",
          "AttendeeId": "...",
          "ExternalUserId": "..."
        },
        "ResponseMetadata": {
          "RequestId": "...",
          "HTTPHeaders": {
            "date": "Thu, 25 Feb 2021 06:51:28 GMT",
            "content-type": "application/json",
            "content-length": "218",
            "x-amzn-requestid": "..."
          },
          "RetryAttempts": 0,
          "HTTPStatusCode": 201
        }
      }

**Comment by timorss** [comment] 2021-02-25 07:58
For me I had to add to app/build.gradle
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.3'
    
![kt](https://user-images.githubusercontent.com/13855015/109121484-f450f480-774f-11eb-92e6-703f721c2ca4.JPG)

**Comment by SuhailBt** [comment] 2021-02-25 19:52
@hokyungh : Anything regarding the above-mentioned issue?

**Comment by hokyungh** [comment] 2021-02-25 20:31
@SuhailBt since you opened another issue. Will close this issue. @timorss feel free to reopen if you still have issue.

Thanks!

**Closed by hokyungh** 2021-02-25 20:31 UTC
Labels: Android, documentation
