### ISSUE TITLE
Zoom in and zoom out feature using amazon chime. We want to zoom in the video tile so that other side person also will see the zoomed In View and same goes while user do zoom out.

### ISSUE THREAD

**Issue by sambeetsahu** [aws-samples/amazon-chime-react-native-demo#156] opened 2022-08-30 09:57 UTC
**Is your feature request related to a problem? Please describe.**
We trying to implement zoom in and zoom out feature using amazon chime. We want to zoom in the video tile so that other side person also will see the zoomed In View and same goes while user do zoom out. Please let us know is there any package that already available on chime sdk that we can use it or if not then how to resolve it.

**Describe the solution you'd like**
We trying to implement zoom in and zoom out feature using amazon chime. We want to zoom in the video tile so that other side person also will see the zoomed In View and same goes while user do zoom out.

**Describe alternatives you've considered**

**Additional context**
We trying to implement zoom in and zoom out feature using amazon chime. We want to zoom in the video tile so that other side person also will see the zoomed In View and same goes while user do zoom out.

**Comment by hokyungh** [comment] 2022-08-30 18:51
Looks like duplicate of https://github.com/aws/amazon-chime-sdk-android/issues/323.

**Closed by hokyungh** 2022-08-30 18:51 UTC
Labels: feature-request

**Comment by sambeetsahu** [comment] 2022-08-30 18:54
Hi hokyung .. so there is no solution for it as of now for this ?
