### ISSUE TITLE
meeting not getting started even after passing proper data - React-native (Android)

### ISSUE THREAD

**Issue by SuhailBt** [aws-samples/amazon-chime-react-native-demo#61] opened 2021-02-25 19:51 UTC
Not able to start meeting while trying 

NativeFunction.startMeeting(meetingJson, attendeeJson);

here are the object structure passing in above function

"meetingJson": {
"ResponseMetadata": {
"RequestId": "id here",
"HTTPStatusCode": 201,
"HTTPHeaders": {
"x-amzn-requestid": "id here from response",
"content-type": "application/json",
"content-length": "841",
"date": "Thu, 25 Feb 2021 06:51:27 GMT"
},
"RetryAttempts": 0
},
"Meeting": {
"MeetingId": "meeting id here,
"ExternalMeetingId": "external meeting id here",
"MediaPlacement": {
"AudioHostUrl": "4df0",
"AudioFallbackUrl": "wss://haxrp.m...",
"ScreenDataUrl": "wss://bit...",
"ScreenSharingUrl": "wss:/...",
"ScreenViewingUrl": "wss://bitp...",
"SignalingUrl": "wss://sig...",
"TurnControlUrl": "ht..."
},
"MediaRegion": "..."
}
},

"attendeeJson": {
"Attendee": {
"JoinToken": "....",
"AttendeeId": "...",
"ExternalUserId": "..."
},
"ResponseMetadata": {
"RequestId": "...",
"HTTPHeaders": {
"date": "Thu, 25 Feb 2021 06:51:28 GMT",
"content-type": "application/json",
"content-length": "218",
"x-amzn-requestid": "..."
},
"RetryAttempts": 0,
"HTTPStatusCode": 201
}
}

Listening to the below mentioned event

    let onErrorSubscription = getSDKEventEmitter().addListener(
      MobileSDKEvent.OnError,
      (message) => {
           ......
      }
    );

instead of 

    let onMeetingStartSubscription = getSDKEventEmitter().addListener(
      MobileSDKEvent.OnMeetingStart,
      () => {
           ......
      }
    );

**Comment by hokyungh** [comment] 2021-02-25 20:30
Hi we might need more information. Any error logs or the behavior you are observing?

**Comment by SuhailBt** [comment] 2021-02-25 20:39
I am getting a response from the api that is called for the meeting creation. That response I am passing in 
NativeFunction.startMeeting(meetingJson, attendeeJson) as mentioned above. 
As expected meeting should start and call onMeetingStart event listener. Instead, it is listening to the onError listener.
I believe the meeting is not getting started from the chime end.

**Comment by SuhailBt** [comment] 2021-02-25 20:45
There is no error. However I am sharing the event that it is listening to (onError listener)

let onErrorSubscription = getSDKEventEmitter().addListener(
  MobileSDKEvent.OnError,
  (message) => {
       console.log(onErrorSubscription)
  }
);

console.log(onErrorSubscription) from the above code consoles  the below-mentioned lines

{"context": undefined, "emitter": {"_subscriber": {"_currentSubscription": null, "_subscriptionsForType": [Object]}}, "eventType": "OnError", "key": 9, "listener": [Function anonymous], "subscriber": {"_currentSubscription": null, "_subscriptionsForType": {"OnError": [Array], "OnMeetingEnd": [Array], "OnMeetingStart": [Array], "RCTDevMenuShown": [Array], "appStateDidChange": [Array], "appearanceChanged": [Array], "collectBugExtraData": [Array], "collectRedBoxExtraData": [Array], "didCompleteNetworkResponse": [Array], "didReceiveNetworkData": [Array], "didReceiveNetworkDataProgress": [Array], "didReceiveNetworkIncrementalData": [Array], "didReceiveNetworkResponse": [Array], "didSendNetworkData": [Array], "didUpdateDimensions": [Array], "hardwareBackPress": [Array], "keyboardDidHide": [Array], "keyboardDidShow": [Array], "keyboardWillHide": [Array], "keyboardWillShow": [Array], "onAnimatedValueUpdate": [Array], "onReanimatedCall": [Array], "onReanimatedPropsChange": [Array], "reduceMotionDidChange": [Array], "toggleElementInspector": [Array], "url": [Array], "websocketClosed": [Array], "websocketFailed": [Array], "websocketMessage": [Array], "websocketOpen": [Array]}}}

**Comment by hokyungh** [comment] 2021-02-25 22:21
Could you do
```
console.log(message)
```

instead of `console.log(onErrorSubscription)` and paste the logs?

Just to make sure. You have 
[MeetingObserver](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/MeetingObservers.kt) and you have [addObservers](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L113)?

**Comment by SuhailBt** [comment] 2021-02-26 06:30
Below is the message I am getting

Error starting the meeting session: Empty list doesn't contain element at index 0.

**Comment by SuhailBt** [comment] 2021-02-26 20:29
Is this of any help?

**Comment by hokyungh** [comment] 2021-02-26 22:06
What SDK version do you use again? I am trying to reproduce this, but having hard time reproducing it?

**Comment by SuhailBt** [comment] 2021-02-26 22:36
29

**Comment by hokyungh** [comment] 2021-02-26 22:38
Sorry. Our mobile SDK/media SDK version.

Basically the following

**Test environment Info (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Version AmazonChimeSDK: [e.g. 0.4.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]

**Comment by SuhailBt** [comment] 2021-02-26 22:45
Device: mi note 8 pro
OS: android 10
Version AmazonChimeSDK: [0.8.0]
Version AmazonChimeSDKMedia: [0.8.0]

**Comment by hokyungh** [comment] 2021-02-27 00:16
Were you able to reproduce it with our demo app? Unfortunately we don't have Mi Note 8 pro, so tested on different Xiaomi devices.

I have tried on
Device: Mi 6 (8), Redmi Note 8 (9)
Version AmazonChimeSDK: 0.8.0
Version AmazonChimeSDKMedia: 0.8.0

Based on logs, it seems to happen after this [line](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L72) since you don't have error log for `Error creating session configuration ....` Do you mind putting debug point after those line to see where it is failing?

**Comment by SuhailBt** [comment] 2021-03-01 10:47
I am not using demo app. I am integrating chime into the existing react-native app. 

I am not able to debug .kt files in react-native. 
I tried to change the exception message in line number 97
  eventEmitter.sendReactNativeEvent(RN_EVENT_ERROR, "Error starting the meeting session: ${exception.localizedMessage}")

to

  eventEmitter.sendReactNativeEvent(RN_EVENT_ERROR, "Error starting the meeting session: ${exception}")

so that I get full exception, not just localizedMessage. But I am getting almost same error. 

Error starting the meeting session: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.

**Comment by hokyungh** [comment] 2021-03-01 22:53
@SuhailBt could you check if [permission](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L86) [permissions](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L51) is not empty?

**Comment by SuhailBt** [comment] 2021-03-01 23:24
When I hit start eeting for the first time on that device, it asked for permissions and I pressed yes. That way permissions should be there.

Is there any way of checking for permissions other than debugging .kt files?

**Comment by hokyungh** [comment] 2021-03-02 00:09
@SuhailBt Do you mind re-downloding https://github.com/aws-samples/amazon-chime-react-native-demo#android and from Android Studio do, File -> Sync Project with Gradle Files and then see if it works?
It should be both 0.8.2 for SDK and media library

And could you copy and paste `AndroidManifest.xml` from your project to here? This should be similar to [AndroidManifest.xml](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/AndroidManifest.xml). I just wanted to see 
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
```
portion.

Could you also put log in [here](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L112) and [here2](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L89) to see if this function runs? You can put

```
  if (!hasPermissionsAlready()) {
      val permissionAwareActivity = activity as PermissionAwareActivity
      permissionAwareActivity.requestPermissions(webRtcPermissionPermission, WEBRTC_PERMISSION_REQUEST_CODE, this)
      return
  }

  logger.info(TAG, "Permission is granted, proceeding to starting meeting");
  startAudioVideo()
```

    private fun startAudioVideo() {
        logger.info(TAG, "Starting meeting current meeting session: ${meetingSession == null}")
        meetingSession?.let {
            it.audioVideo.addRealtimeObserver(meetingObservers)
            it.audioVideo.addVideoTileObserver(meetingObservers)
            it.audioVideo.addAudioVideoObserver(meetingObservers)
            it.audioVideo.start()
            it.audioVideo.startRemoteVideo()
        }
    }
```

If you could provide logs for it, it could help us to further diagnose the issue. Thanks!

**Comment by SuhailBt** [comment] 2021-03-02 00:41
I downloaded and synced the .aar files again. It is still not working. 
Attaching screenshot of AndroidManifest.xml file. Those permissions are mentioned there.
![Screenshot from 2021-03-02 05-53-09](https://user-images.githubusercontent.com/65166275/109578824-e3243100-7b1d-11eb-9948-1857b1aa91ce.png)

After adding logger.info statements as mentioned above, where should I check for logs?  Excuse me for that, but I have no idea about .kt files and logging in .kt files.

**Comment by SuhailBt** [comment] 2021-03-02 02:14
@hokyungh Do I need to make any changes with these imports in NativeMobileSDKPackage.kt file

import com.amazonaws.services.chime.sdk.meetings.session.DefaultMeetingSession
import com.amazonaws.services.chime.sdk.meetings.session.MeetingSession
import com.amazonaws.services.chime.sdk.meetings.session.MeetingSessionConfiguration
import com.amazonaws.services.chime.sdk.meetings.session.MeetingSessionCredentials
import com.amazonaws.services.chime.sdk.meetings.session.MeetingSessionURLs
import com.amazonaws.services.chime.sdk.meetings.session.defaultUrlRewriter
import com.amazonaws.services.chime.sdk.meetings.utils.logger.ConsoleLogger
import com.amazonaws.services.chime.sdk.meetings.utils.logger.LogLevel

my project package is as 

package com.ispl.squarecruit

in the same file

**Comment by hokyungh** [comment] 2021-03-02 17:24
@SuhailBt those imports don't need to be changed. Do you have full logs by any chance? You can use either [logcat](https://developer.android.com/studio/command-line/logcat) or use Android Studio to open the logcat.

**Comment by SuhailBt** [comment] 2021-03-03 05:32
@hokyungh Thanks a lot for the help. Attaching the screenshot for logs

![Screenshot from 2021-03-03 11-00-39](https://user-images.githubusercontent.com/65166275/109757515-f44d6a80-7c0f-11eb-9a3b-25a47635aa68.png)

**Comment by hokyungh** [comment] 2021-03-03 19:33
Was there any change in the code of `NativeMobileSDKBridge` and `MeetingObservers`? I double checked our code, but I couldn't find any indexing in our logic.

**Comment by SuhailBt** [comment] 2021-03-03 19:40
No change at all. I have added the same files as in demo app.

**Comment by SuhailBt** [comment] 2021-03-03 19:59
I removed previous files and downloaded again from  demo app and run again. Same error

![Screenshot from 2021-03-04 01-28-44](https://user-images.githubusercontent.com/65166275/109864645-13d4a980-7c89-11eb-979c-f60c37adfd57.png)

**Comment by hokyungh** [comment] 2021-03-03 20:01
I think we might need to start from beginning. 

From Android Studio, could you do `Build->Clean Project` and then  `File -> Invalidate Caches / Restart` and restart Android Studio. After restarting, Could you do `File -> Sync Project With Gradle Files`?

Could you also list out files you have in your directories such as folder structures and files in each folder.

Lastly, could you add little more logs and paste the logs to me?
```
    private fun startAudioVideo() {
        logger.info(TAG, "Starting meeting current meeting session: ${meetingSession == null}")
        meetingSession?.let {
            it.audioVideo.addRealtimeObserver(meetingObservers)
             logger.info(TAG, "Observers added 1")
            it.audioVideo.addVideoTileObserver(meetingObservers)
             logger.info(TAG, "Observers added 2")
            it.audioVideo.addAudioVideoObserver(meetingObservers)
            logger.info(TAG, "Observers added 3")
            it.audioVideo.start()
            logger.info(TAG, "Meeting Start requested")
        }
    }
```

**Comment by SuhailBt** [comment] 2021-03-03 20:28
I followed the above provided steps, but still getting the same error.
Attaching screenshots for you reference
![Screenshot from 2021-03-04 01-47-33](https://user-images.githubusercontent.com/65166275/109867977-2224c480-7c8d-11eb-8b97-a5847a6c6301.png)
![Screenshot from 2021-03-04 01-47-54](https://user-images.githubusercontent.com/65166275/109867983-2355f180-7c8d-11eb-8653-97b972bde4ae.png)
![Screenshot from 2021-03-04 01-48-03](https://user-images.githubusercontent.com/65166275/109867988-23ee8800-7c8d-11eb-9b59-fb30f5cde22b.png)
![Screenshot from 2021-03-04 01-48-55](https://user-images.githubusercontent.com/65166275/109867991-24871e80-7c8d-11eb-8663-779a158e7fc7.png)
![Screenshot from 2021-03-04 01-55-03](https://user-images.githubusercontent.com/65166275/109867995-25b84b80-7c8d-11eb-962b-755cd17a037e.png)

**Comment by SuhailBt** [comment] 2021-03-03 20:42
I observed this log is not printed

logger.info(TAG, "Meeting Start requested")

**Comment by SuhailBt** [comment] 2021-03-04 17:43
@dylonChime Could you help me with the time it may take? And do you need any more inputs from me?

**Comment by hokyungh** [comment] 2021-03-05 08:58
@SuhailBt is there a way for us know what's the code in the `App.js`?

I was able to reproduce it by doing 
`meetingResponse.JoinInfo.Meeting.Meeting.MediaPlacement.AudioHostUrl = "";`

```
    createMeetingRequest(meetingName, userName).then(meetingResponse => {
      this.setState({
        meetingTitle: meetingName,
        selfAttendeeId: meetingResponse.JoinInfo.Attendee.Attendee.AttendeeId
      })
      meetingResponse.JoinInfo.Meeting.Meeting.MediaPlacement.AudioHostUrl = "";
      NativeFunction.startMeeting(meetingResponse.JoinInfo.Meeting.Meeting, meetingResponse.JoinInfo.Attendee.Attendee);
    }).catch(error => {
      Alert.alert("Unable to find meeting", `There was an issue finding that meeting. The meeting may have already ended, or your authorization may have expired.\n ${error}`);
      this.setState({ isLoading: false });
    });
```

I have tried the other values, but it seems that empty is the only way to get index error

The other way I was able to get index error was overriding the rewriter to just return empty string
For instance, [line](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L142)
```
    private fun emptyUrlRewriter(s: String): String {
        return ""
    }

 MeetingSessionURLs(audioFallbackUrl, audioHostUrl, turnControlUrl, signalingUrl, ::emptyUrlRewriter))
```
but since you said you didn't touch `NativeMobileSDKBridge.kt.` AudioHostUrl becoming empty seems to be most plausible scenario.

Could you do this logging one more time on [line](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L72)?
```
   try {
          logger.info(TAG, "Test: $meetingInfo")
          val sessionConfig = createSessionConfiguration(meetingInfo, attendeeInfo)
```

and before this [line](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/android/app/src/main/java/com/amazonaws/services/chime/rndemo/NativeMobileSDKBridge.kt#L140)

```

  logger.info(TAG, "audioHostUrl: $audioHostUrl")

  logger.info(TAG, "Test2: 1. $meetingId 2. $attendeeId 3. $joinToken 4. $externalUserId 5. $audioFallbackUrl 6. $audioHostUrl 7. $turnControlUrl 8. $signalingUrl")

  MeetingSessionConfiguration(meetingId,
          MeetingSessionCredentials(attendeeId, externalUserId, joinToken),
          MeetingSessionURLs(audioFallbackUrl, audioHostUrl, turnControlUrl, signalingUrl, ::defaultUrlRewriter))
```

When you give us logs, you can shrink some of sensitive information like token, id, urls. I just want to make sure that these are not empty.

**Comment by SuhailBt** [comment] 2021-03-05 14:54
@hokyungh  I am not using app.js for any of this process. I am directly calling python API that is already available for our platform and tested as well. We have a working API that we used for chime integration with the js library provided. The same API I am using to get meeting info and the response structure I am getting from that API is mentioned in the above comments.

I debugged these steps as mentioned by you and I observed even though the value for audioHostUrl is there, these lines of code is not able to fetch it from the present object.

         val meetingId = meetingInfo.getString(KEY_MEETING_ID) ?: ""
            val attendeeId = attendeeInfo.getString(KEY_ATTENDEE_ID) ?: ""
            val joinToken = attendeeInfo.getString(KEY_JOIN_TOKEN) ?: ""
            val externalUserId = attendeeInfo.getString(KEY_EXTERNAL_ID) ?: ""
            var audioFallbackUrl = ""
            var audioHostUrl = ""
            var turnControlUrl = ""
            var signalingUrl = ""

            meetingInfo.getMap(KEY_MEDIA_PLACEMENT)?.let {
                logger.info(TAG, it.toString())
                audioFallbackUrl = it.getString(KEY_AUDIO_FALLBACK_URL) ?: ""
                audioHostUrl = it.getString(KEY_AUDIO_HOST_URL) ?: ""
                turnControlUrl = it.getString(KEY_TURN_CONTROL_URL) ?: ""
                signalingUrl = it.getString(KEY_SIGNALING_URL) ?: ""
            }
line 122-140 in NativeMobileSDKBridge.kt.
I am attaching a log snapshot as well for your reference. 
I believe the above-mentioned code has to be tweaked a bit to get those values.

![Screenshot from 2021-03-05 19-58-20](https://user-images.githubusercontent.com/65166275/110132056-c5dab580-7df0-11eb-8be7-a1726cc32358.png)

**Comment by SuhailHassan** [comment] 2021-03-05 19:39
Test

**Comment by hokyungh** [comment] 2021-03-05 20:02
@SuhailBt based on the logs, it looks like the one passed to the Android Native side doesn't seem to be correct. Could you check in the [line](https://github.com/aws-samples/amazon-chime-react-native-demo/blob/master/src/App.js#L67) that the one you passed it Meeting.Meeting? 

The logs still contains `Meeting` as key while the expected printed version should be
```
{ NativeMap: {"MediaRegion":"u...","MediaPlacement":{"TurnControlUrl":"https://...","SignalingUrl":"wss://...","ScreenViewingUrl":"wss://...","ScreenSharingUrl":"wss://...","ScreenDataUrl":"wss://...","AudioFallbackUrl":"wss://...","AudioHostUrl":"ce...."},"ExternalMeetingId":"externalId","MeetingId":"meetingid"} }
```

but yours contains `{ NativeMap: "Meeting": {....`

**Comment by SuhailBt** [comment] 2021-03-05 20:27
> Not able to start meeting while trying
> 
> NativeFunction.startMeeting(meetingJson, attendeeJson);
> 
> here are the object structure passing in above function
> 
> "meetingJson": {
> "ResponseMetadata": {
> "RequestId": "id here",
> "HTTPStatusCode": 201,
> "HTTPHeaders": {
> "x-amzn-requestid": "id here from response",
> "content-type": "application/json",
> "content-length": "841",
> "date": "Thu, 25 Feb 2021 06:51:27 GMT"
> },
> "RetryAttempts": 0
> },
> "Meeting": {
> "MeetingId": "meeting id here,
> "ExternalMeetingId": "external meeting id here",
> "MediaPlacement": {
> "AudioHostUrl": "4df0",
> "AudioFallbackUrl": "wss://haxrp.m...",
> "ScreenDataUrl": "wss://bit...",
> "ScreenSharingUrl": "wss:/...",
> "ScreenViewingUrl": "wss://bitp...",
> "SignalingUrl": "wss://sig...",
> "TurnControlUrl": "ht..."
> },
> "MediaRegion": "..."
> }
> },
> 
> "attendeeJson": {
> "Attendee": {
> "JoinToken": "....",
> "AttendeeId": "...",
> "ExternalUserId": "..."
> },
> "ResponseMetadata": {
> "RequestId": "...",
> "HTTPHeaders": {
> "date": "Thu, 25 Feb 2021 06:51:28 GMT",
> "content-type": "application/json",
> "content-length": "218",
> "x-amzn-requestid": "..."
> },
> "RetryAttempts": 0,
> "HTTPStatusCode": 201
> }
> }
> 
> Listening to the below mentioned event
> 
> ```
> let onErrorSubscription = getSDKEventEmitter().addListener(
>   MobileSDKEvent.OnError,
>   (message) => {
>        ......
>   }
> );
> ```
> 
> instead of
> 
> ```
> let onMeetingStartSubscription = getSDKEventEmitter().addListener(
>   MobileSDKEvent.OnMeetingStart,
>   () => {
>        ......
>   }
> );
> ```

This is the objects structure I am passing. Could you suggest the changes needed in these?

**Comment by hokyungh** [comment] 2021-03-05 20:30
Could you try `meetingJson["Meeting"] and attendeeJson["Attendee"]`?

**Comment by SuhailBt** [comment] 2021-03-05 20:47
Yes OnMeetingStart handler Is called after doing this change. 
Appreciate your help. Bravo.

**Comment by hokyungh** [comment] 2021-03-05 22:26
Glad it worked. Will close this issue. Feel free to open it if you have further issue.

**Closed by hokyungh** 2021-03-05 22:26 UTC
Labels: needs investigation
